//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Session LogInSessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Registration[] RegistrationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaltField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Session LogInSession {
            get {
                return this.LogInSessionField;
            }
            set {
                if ((object.ReferenceEquals(this.LogInSessionField, value) != true)) {
                    this.LogInSessionField = value;
                    this.RaisePropertyChanged("LogInSession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Registration[] Registrations {
            get {
                return this.RegistrationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationsField, value) != true)) {
                    this.RegistrationsField = value;
                    this.RaisePropertyChanged("Registrations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireDate {
            get {
                return this.ExpireDateField;
            }
            set {
                if ((this.ExpireDateField.Equals(value) != true)) {
                    this.ExpireDateField = value;
                    this.RaisePropertyChanged("ExpireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registration", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Registration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Event EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Item[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfCreation {
            get {
                return this.DateOfCreationField;
            }
            set {
                if ((this.DateOfCreationField.Equals(value) != true)) {
                    this.DateOfCreationField = value;
                    this.RaisePropertyChanged("DateOfCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Event Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Item[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.User AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Component[] ComponentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfParticipantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Registration[] RegistrationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.User Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminField, value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Component[] Components {
            get {
                return this.ComponentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComponentsField, value) != true)) {
                    this.ComponentsField = value;
                    this.RaisePropertyChanged("Components");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datetime {
            get {
                return this.DatetimeField;
            }
            set {
                if ((this.DatetimeField.Equals(value) != true)) {
                    this.DatetimeField = value;
                    this.RaisePropertyChanged("Datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublic {
            get {
                return this.IsPublicField;
            }
            set {
                if ((this.IsPublicField.Equals(value) != true)) {
                    this.IsPublicField = value;
                    this.RaisePropertyChanged("IsPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfParticipants {
            get {
                return this.NumOfParticipantsField;
            }
            set {
                if ((this.NumOfParticipantsField.Equals(value) != true)) {
                    this.NumOfParticipantsField = value;
                    this.RaisePropertyChanged("NumOfParticipants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceFrom {
            get {
                return this.PriceFromField;
            }
            set {
                if ((this.PriceFromField.Equals(value) != true)) {
                    this.PriceFromField = value;
                    this.RaisePropertyChanged("PriceFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceTo {
            get {
                return this.PriceToField;
            }
            set {
                if ((this.PriceToField.Equals(value) != true)) {
                    this.PriceToField = value;
                    this.RaisePropertyChanged("PriceTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Registration[] Registrations {
            get {
                return this.RegistrationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationsField, value) != true)) {
                    this.RegistrationsField = value;
                    this.RaisePropertyChanged("Registrations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Item : Web.ServiceReference.Component {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Registration RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegistrationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Registration Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationField, value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegistrationId {
            get {
                return this.RegistrationIdField;
            }
            set {
                if ((this.RegistrationIdField.Equals(value) != true)) {
                    this.RegistrationIdField = value;
                    this.RaisePropertyChanged("RegistrationId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Component", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.ServiceReference.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.ServiceReference.Item))]
    public partial class Component : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Event EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Component ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Event Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Component Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Category : Web.ServiceReference.Component {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ServiceReference.Component[] ComponentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ServiceReference.Component[] Components {
            get {
                return this.ComponentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComponentsField, value) != true)) {
                    this.ComponentsField = value;
                    this.RaisePropertyChanged("Components");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        void CreateUser(string firstname, string lastname, string pmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string firstname, string lastname, string pmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogIn", ReplyAction="http://tempuri.org/IService/LogInResponse")]
        Web.ServiceReference.User LogIn(string email, string clearTextPw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogIn", ReplyAction="http://tempuri.org/IService/LogInResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference.User> LogInAsync(string email, string clearTextPw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateEvent", ReplyAction="http://tempuri.org/IService/CreateEventResponse")]
        Web.ServiceReference.Event CreateEvent(string title, string description, int numOfParticipants, double priceFrom, double priceTo, string location, System.DateTime datetime, bool isPublic, Web.ServiceReference.User admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateEvent", ReplyAction="http://tempuri.org/IService/CreateEventResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference.Event> CreateEventAsync(string title, string description, int numOfParticipants, double priceFrom, double priceTo, string location, System.DateTime datetime, bool isPublic, Web.ServiceReference.User admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindEventById", ReplyAction="http://tempuri.org/IService/FindEventByIdResponse")]
        Web.ServiceReference.Event FindEventById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindEventById", ReplyAction="http://tempuri.org/IService/FindEventByIdResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference.Event> FindEventByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SignUpForEvent", ReplyAction="http://tempuri.org/IService/SignUpForEventResponse")]
        void SignUpForEvent(string userEmail, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SignUpForEvent", ReplyAction="http://tempuri.org/IService/SignUpForEventResponse")]
        System.Threading.Tasks.Task SignUpForEventAsync(string userEmail, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsRegisteredToEvent", ReplyAction="http://tempuri.org/IService/IsRegisteredToEventResponse")]
        bool IsRegisteredToEvent(Web.ServiceReference.User u, Web.ServiceReference.Event e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsRegisteredToEvent", ReplyAction="http://tempuri.org/IService/IsRegisteredToEventResponse")]
        System.Threading.Tasks.Task<bool> IsRegisteredToEventAsync(Web.ServiceReference.User u, Web.ServiceReference.Event e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindCategoryById", ReplyAction="http://tempuri.org/IService/FindCategoryByIdResponse")]
        Web.ServiceReference.Category FindCategoryById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindCategoryById", ReplyAction="http://tempuri.org/IService/FindCategoryByIdResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference.Category> FindCategoryByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUserInfo", ReplyAction="http://tempuri.org/IService/UpdateUserInfoResponse")]
        Web.ServiceReference.User UpdateUserInfo(Web.ServiceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUserInfo", ReplyAction="http://tempuri.org/IService/UpdateUserInfoResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference.User> UpdateUserInfoAsync(Web.ServiceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddCategoryToEvent", ReplyAction="http://tempuri.org/IService/AddCategoryToEventResponse")]
        void AddCategoryToEvent(int eventId, string categoryTitle, string categoryDescription, Web.ServiceReference.Component parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddCategoryToEvent", ReplyAction="http://tempuri.org/IService/AddCategoryToEventResponse")]
        System.Threading.Tasks.Task AddCategoryToEventAsync(int eventId, string categoryTitle, string categoryDescription, Web.ServiceReference.Component parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddItemToCategory", ReplyAction="http://tempuri.org/IService/AddItemToCategoryResponse")]
        void AddItemToCategory(int eventId, int categoryId, int amount, string itemTitle, string itemDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddItemToCategory", ReplyAction="http://tempuri.org/IService/AddItemToCategoryResponse")]
        System.Threading.Tasks.Task AddItemToCategoryAsync(int eventId, int categoryId, int amount, string itemTitle, string itemDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindComponentByParentId", ReplyAction="http://tempuri.org/IService/FindComponentByParentIdResponse")]
        Web.ServiceReference.Component[] FindComponentByParentId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindComponentByParentId", ReplyAction="http://tempuri.org/IService/FindComponentByParentIdResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference.Component[]> FindComponentByParentIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetInviteString", ReplyAction="http://tempuri.org/IService/GetInviteStringResponse")]
        string GetInviteString(Web.ServiceReference.Event evnt, Web.ServiceReference.User usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetInviteString", ReplyAction="http://tempuri.org/IService/GetInviteStringResponse")]
        System.Threading.Tasks.Task<string> GetInviteStringAsync(Web.ServiceReference.Event evnt, Web.ServiceReference.User usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AcceptInviteString", ReplyAction="http://tempuri.org/IService/AcceptInviteStringResponse")]
        Web.ServiceReference.Event AcceptInviteString(Web.ServiceReference.User usr, string inviteString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AcceptInviteString", ReplyAction="http://tempuri.org/IService/AcceptInviteStringResponse")]
        System.Threading.Tasks.Task<Web.ServiceReference.Event> AcceptInviteStringAsync(Web.ServiceReference.User usr, string inviteString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SignUpForItem", ReplyAction="http://tempuri.org/IService/SignUpForItemResponse")]
        void SignUpForItem(string userEmail, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SignUpForItem", ReplyAction="http://tempuri.org/IService/SignUpForItemResponse")]
        System.Threading.Tasks.Task SignUpForItemAsync(string userEmail, int itemId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Web.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Web.ServiceReference.IService>, Web.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateUser(string firstname, string lastname, string pmail, string password) {
            base.Channel.CreateUser(firstname, lastname, pmail, password);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string firstname, string lastname, string pmail, string password) {
            return base.Channel.CreateUserAsync(firstname, lastname, pmail, password);
        }
        
        public Web.ServiceReference.User LogIn(string email, string clearTextPw) {
            return base.Channel.LogIn(email, clearTextPw);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference.User> LogInAsync(string email, string clearTextPw) {
            return base.Channel.LogInAsync(email, clearTextPw);
        }
        
        public Web.ServiceReference.Event CreateEvent(string title, string description, int numOfParticipants, double priceFrom, double priceTo, string location, System.DateTime datetime, bool isPublic, Web.ServiceReference.User admin) {
            return base.Channel.CreateEvent(title, description, numOfParticipants, priceFrom, priceTo, location, datetime, isPublic, admin);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference.Event> CreateEventAsync(string title, string description, int numOfParticipants, double priceFrom, double priceTo, string location, System.DateTime datetime, bool isPublic, Web.ServiceReference.User admin) {
            return base.Channel.CreateEventAsync(title, description, numOfParticipants, priceFrom, priceTo, location, datetime, isPublic, admin);
        }
        
        public Web.ServiceReference.Event FindEventById(int id) {
            return base.Channel.FindEventById(id);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference.Event> FindEventByIdAsync(int id) {
            return base.Channel.FindEventByIdAsync(id);
        }
        
        public void SignUpForEvent(string userEmail, int eventId) {
            base.Channel.SignUpForEvent(userEmail, eventId);
        }
        
        public System.Threading.Tasks.Task SignUpForEventAsync(string userEmail, int eventId) {
            return base.Channel.SignUpForEventAsync(userEmail, eventId);
        }
        
        public bool IsRegisteredToEvent(Web.ServiceReference.User u, Web.ServiceReference.Event e) {
            return base.Channel.IsRegisteredToEvent(u, e);
        }
        
        public System.Threading.Tasks.Task<bool> IsRegisteredToEventAsync(Web.ServiceReference.User u, Web.ServiceReference.Event e) {
            return base.Channel.IsRegisteredToEventAsync(u, e);
        }
        
        public Web.ServiceReference.Category FindCategoryById(int id) {
            return base.Channel.FindCategoryById(id);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference.Category> FindCategoryByIdAsync(int id) {
            return base.Channel.FindCategoryByIdAsync(id);
        }
        
        public Web.ServiceReference.User UpdateUserInfo(Web.ServiceReference.User u) {
            return base.Channel.UpdateUserInfo(u);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference.User> UpdateUserInfoAsync(Web.ServiceReference.User u) {
            return base.Channel.UpdateUserInfoAsync(u);
        }
        
        public void AddCategoryToEvent(int eventId, string categoryTitle, string categoryDescription, Web.ServiceReference.Component parent) {
            base.Channel.AddCategoryToEvent(eventId, categoryTitle, categoryDescription, parent);
        }
        
        public System.Threading.Tasks.Task AddCategoryToEventAsync(int eventId, string categoryTitle, string categoryDescription, Web.ServiceReference.Component parent) {
            return base.Channel.AddCategoryToEventAsync(eventId, categoryTitle, categoryDescription, parent);
        }
        
        public void AddItemToCategory(int eventId, int categoryId, int amount, string itemTitle, string itemDescription) {
            base.Channel.AddItemToCategory(eventId, categoryId, amount, itemTitle, itemDescription);
        }
        
        public System.Threading.Tasks.Task AddItemToCategoryAsync(int eventId, int categoryId, int amount, string itemTitle, string itemDescription) {
            return base.Channel.AddItemToCategoryAsync(eventId, categoryId, amount, itemTitle, itemDescription);
        }
        
        public Web.ServiceReference.Component[] FindComponentByParentId(int id) {
            return base.Channel.FindComponentByParentId(id);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference.Component[]> FindComponentByParentIdAsync(int id) {
            return base.Channel.FindComponentByParentIdAsync(id);
        }
        
        public string GetInviteString(Web.ServiceReference.Event evnt, Web.ServiceReference.User usr) {
            return base.Channel.GetInviteString(evnt, usr);
        }
        
        public System.Threading.Tasks.Task<string> GetInviteStringAsync(Web.ServiceReference.Event evnt, Web.ServiceReference.User usr) {
            return base.Channel.GetInviteStringAsync(evnt, usr);
        }
        
        public Web.ServiceReference.Event AcceptInviteString(Web.ServiceReference.User usr, string inviteString) {
            return base.Channel.AcceptInviteString(usr, inviteString);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReference.Event> AcceptInviteStringAsync(Web.ServiceReference.User usr, string inviteString) {
            return base.Channel.AcceptInviteStringAsync(usr, inviteString);
        }
        
        public void SignUpForItem(string userEmail, int itemId) {
            base.Channel.SignUpForItem(userEmail, itemId);
        }
        
        public System.Threading.Tasks.Task SignUpForItemAsync(string userEmail, int itemId) {
            return base.Channel.SignUpForItemAsync(userEmail, itemId);
        }
    }
}
